---
#
# This playbook creates configs, but will not deploy them
#
- name: Manage Arista EOS EVPN/VXLAN Configuration
  hosts: AVD_FABRIC
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  vars:
    fabric_dir_name: "{{fabric_name}}"
    execute_tasks: false
  tasks:
    - name: 'reset local folders for output'
      tags: [build, generate]
      import_role:
        name: arista.avd.build_output_folders

    - name: generate intended variables
      tags: [build, generate]
      import_role:
        name: arista.avd.eos_designs

    - name: generate device intended config and documentation
      tags: [build, generate]
      import_role:
        name: eos_cli_config_gen
